[book]
authors = ["Ingonyama"]
language = "ch"
multilingual = false
src = "zh"
title = "Ingopedia"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/0xdwong/ingopedia"
edit-url-template = " https://github.com/0xdwong/ingopedia/edit/master/{path}"

[output.html.print]
page-break = false

[preprocessor.katex]
after = ["links"]
